name: bpm
description: Cross-platform BPM detection tool built with Flutter and multi-algorithm DSP pipeline.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  record: ^6.1.2
  just_audio: ^0.10.5
  collection: ^1.18.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.26.2
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/branding/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/branding/app_icon.png
  image_path_svg: assets/branding/app_icon.svg
