name: bpm
description: Cross-platform BPM detection tool built with Flutter and multi-algorithm DSP pipeline.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  record: ^5.0.1
  just_audio: ^0.9.36
  fftea: ^1.3.0
  collection: ^1.18.0
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  test: ^1.25.2

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
